name: Publish version on release

on:
  release:
    types: [published]   

permissions:
  contents: write       

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare version folder
        run: |
          VERSION="v${{ github.event.release.tag_name }}"
          mkdir -p _site/$VERSION
          cp -R index.html en ru _site/$VERSION/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: true
