name: doc
on:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/cheackout@v3
    
    - name: Set
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

  check:
      runs-on: ubuntu-latest
        
      steps:
      - name: Files view
        run: dir ./*
          
          
